server:
  port: 8080
  tomcat:
    connection-timeout: 300000

spring:
  mvc:
    async:
      request-timeout: 300000

spark:
  hdfs:
    url: hdfs://localhost:9000
  master: local[*]
  app-name: AisDataQueryService
